# Generated by Django 4.2.7 on 2026-04-25 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_projectmodulebinding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrEngineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('engine_type', models.CharField(choices=[('gpt4v', 'GPT-4V'), ('glm4v', 'GLM-4V'), ('tesseract', 'Tesseract'), ('custom', 'Custom')], max_length=30)),
                ('base_url', models.CharField(blank=True, max_length=500)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('credential_ref', models.CharField(blank=True, max_length=200)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_engine_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ocr_engine_configs',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OcrTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('text', 'Text'), ('other', 'Other')], default='image', max_length=20)),
                ('input_url', models.CharField(blank=True, max_length=1000)),
                ('original_filename', models.CharField(blank=True, max_length=300)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_tasks', to=settings.AUTH_USER_MODEL)),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ocr_service.ocrengineconfig')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_tasks', to='projects.project')),
            ],
            options={
                'db_table': 'ocr_tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='ocr_tasks_project_b29ef0_idx'), models.Index(fields=['created_by', '-created_at'], name='ocr_tasks_created_b3e491_idx'), models.Index(fields=['engine', 'status'], name='ocr_tasks_engine__3ceb45_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ocrengineconfig',
            index=models.Index(fields=['created_by', 'is_active'], name='ocr_engine__created_df0a12_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrengineconfig',
            index=models.Index(fields=['engine_type'], name='ocr_engine__engine__ff3bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrengineconfig',
            index=models.Index(fields=['is_default'], name='ocr_engine__is_defa_8829d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ocrengineconfig',
            unique_together={('created_by', 'name')},
        ),
    ]
