# Generated by Django 4.2.7 on 2026-04-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtask',
            name='input_text',
            field=models.TextField(blank=True),
        ),
    ]
