# Generated by Django 4.2.7 on 2026-04-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_service', '0002_ocrtask_input_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrtask',
            name='input_file',
            field=models.FileField(blank=True, null=True, upload_to='ocr_service/tasks/%Y/%m/'),
        ),
    ]
