# Generated by Django 4.2.7 on 2026-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_service', '0003_ocrtask_input_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrengineconfig',
            name='engine_type',
            field=models.CharField(choices=[('gpt4v', 'GPT-4V'), ('glm4v', 'GLM-4V'), ('easyocr', 'EasyOCR'), ('tesseract', 'Tesseract'), ('custom', 'Custom')], max_length=30),
        ),
    ]
