# Generated by Django 4.2.7 on 2026-04-27 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_service', '0005_ocrbatch_ocrengineconfig_last_check_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ocr_service.ocrtask')),
            ],
            options={
                'db_table': 'ocr_pages',
                'ordering': ['task_id', 'page_number'],
                'indexes': [models.Index(fields=['task', 'page_number'], name='ocr_pages_task_id_d2cecd_idx'), models.Index(fields=['page_number'], name='ocr_pages_page_nu_c2401f_idx')],
                'unique_together': {('task', 'page_number')},
            },
        ),
    ]
