# Generated by Django 4.2.7 on 2026-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('browser_use_text', 'Browser Use - 文本模式'), ('browser_use_vision', 'Browser Use - 视觉模式')], max_length=20, verbose_name='角色'),
        ),
    ]
