# Generated by Django 4.2.7 on 2026-05-01 10:51

import apps.core.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requirement_analysis', '0002_alter_aimodelconfig_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='api_key',
            field=apps.core.encrypted_fields.EncryptedCharField(blank=True, max_length=2048, null=True, verbose_name='API Key'),
        ),
    ]
