# Generated by Django 4.2.7 on 2026-04-23 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModuleBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('api_testing', 'API Testing'), ('ui_automation', 'UI Automation'), ('app_automation', 'APP Automation')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_bindings', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project module binding',
                'verbose_name_plural': 'Project module bindings',
                'db_table': 'project_module_bindings',
                'indexes': [models.Index(fields=['project', 'module'], name='project_mod_project_6e38d0_idx'), models.Index(fields=['module', 'object_id'], name='project_mod_module_662ac1_idx')],
                'unique_together': {('module', 'object_id')},
            },
        ),
    ]
