# Generated by Django 4.2.7 on 2026-04-25 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_projectmodulebinding'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedTestAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('manual', 'Manual'), ('api_testing', 'API Testing'), ('ui_automation', 'UI Automation'), ('app_automation', 'APP Automation'), ('ai_testing', 'AI Testing')], max_length=50)),
                ('asset_type', models.CharField(choices=[('testcase', 'Test Case'), ('testsuite', 'Test Suite'), ('review', 'Review')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('priority', models.CharField(blank=True, default='', max_length=50)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('version_label', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_assets', to='projects.project')),
            ],
            options={
                'db_table': 'unified_test_assets',
                'ordering': ['-source_updated_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedTestAssetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_hash', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.unifiedtestasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unified_test_asset_snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset', '-created_at'], name='unified_tes_asset_i_a9c13b_idx'), models.Index(fields=['snapshot_hash'], name='unified_tes_snapsho_ad938e_idx')],
                'unique_together': {('asset', 'snapshot_hash')},
            },
        ),
        migrations.AddIndex(
            model_name='unifiedtestasset',
            index=models.Index(fields=['project', 'asset_type'], name='unified_tes_project_98ba6a_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedtestasset',
            index=models.Index(fields=['module', 'asset_type'], name='unified_tes_module_5233a9_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedtestasset',
            index=models.Index(fields=['status'], name='unified_tes_status_260a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedtestasset',
            index=models.Index(fields=['priority'], name='unified_tes_priorit_8a5012_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedtestasset',
            index=models.Index(fields=['source_updated_at'], name='unified_tes_source__faf7e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unifiedtestasset',
            unique_together={('module', 'asset_type', 'object_id')},
        ),
    ]
