# Generated by Django 4.2.7 on 2026-04-26 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_unifiedtestasset_unifiedtestassetsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPermissionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='*', max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('allowed_roles', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_permission_policies', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_policies', to='projects.project')),
            ],
            options={
                'db_table': 'project_permission_policies',
                'ordering': ['project_id', 'module', 'action', '-updated_at'],
                'indexes': [models.Index(fields=['project', 'module', 'action'], name='project_per_project_5cb87c_idx'), models.Index(fields=['is_active'], name='project_per_is_acti_408b0b_idx')],
                'unique_together': {('project', 'module', 'action')},
            },
        ),
    ]
