# Generated by Django 4.2.7 on 2026-04-27 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_projectpermissionpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('meta_project', 'Meta Project'), ('module_project', 'Module Project')], default='meta_project', max_length=30)),
                ('module', models.CharField(blank=True, default='', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '暂停'), ('completed', '已完成'), ('archived', '已归档')], default='active', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_meta_projects', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.metaproject')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_nodes', to='projects.project')),
            ],
            options={
                'db_table': 'meta_projects',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['project', 'parent'], name='meta_projec_project_a3a76e_idx'), models.Index(fields=['project', 'module', 'object_id'], name='meta_projec_project_cdfc07_idx'), models.Index(fields=['owner'], name='meta_projec_owner_i_548636_idx')],
            },
        ),
    ]
