# Generated by Django 4.2.7 on 2026-04-17 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFactoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100, verbose_name='工具名称')),
                ('tool_category', models.CharField(choices=[('test_data', '测试数据'), ('json', 'JSON工具'), ('string', '字符工具'), ('encoding', '编码工具'), ('random', '随机工具'), ('encryption', '加密工具'), ('crontab', 'Crontab工具')], max_length=20, verbose_name='工具分类')),
                ('tool_scenario', models.CharField(choices=[('test_data', '测试数据'), ('json', 'JSON工具'), ('string', '字符工具'), ('encoding', '编码工具'), ('random', '随机工具'), ('encryption', '加密工具'), ('crontab', 'Crontab工具')], max_length=20, verbose_name='使用场景')),
                ('input_data', models.JSONField(blank=True, null=True, verbose_name='输入数据')),
                ('output_data', models.JSONField(verbose_name='输出数据')),
                ('is_saved', models.BooleanField(default=True, verbose_name='是否保存')),
                ('tags', models.JSONField(blank=True, null=True, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '数据工厂记录',
                'verbose_name_plural': '数据工厂记录',
                'db_table': 'data_factory_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='data_factor_user_id_7c734a_idx'), models.Index(fields=['tool_category'], name='data_factor_tool_ca_c12b1d_idx'), models.Index(fields=['tool_scenario'], name='data_factor_tool_sc_820bde_idx'), models.Index(fields=['user', 'tool_category'], name='data_factor_user_id_c91ac7_idx'), models.Index(fields=['user', 'tool_scenario'], name='data_factor_user_id_580464_idx'), models.Index(fields=['user', 'is_saved'], name='data_factor_user_id_454377_idx')],
            },
        ),
    ]
