# Generated by Django 4.2.7 on 2026-04-17 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('testcases', '0001_initial'),
        ('versions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, verbose_name='计划描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignees', models.ManyToManyField(blank=True, related_name='assigned_plans', to=settings.AUTH_USER_MODEL, verbose_name='指派给')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('projects', models.ManyToManyField(blank=True, related_name='test_plans', to='projects.project', verbose_name='关联项目')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='versions.version', verbose_name='关联版本')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'db_table': 'test_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='执行名称')),
                ('description', models.TextField(blank=True, verbose_name='执行描述')),
                ('status', models.CharField(choices=[('untested', '未测试'), ('in_progress', '进行中'), ('completed', '已完成'), ('blocked', '阻塞')], default='untested', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_runs', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_runs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='projects.project', verbose_name='关联项目')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='executions.testplan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': '测试执行',
                'verbose_name_plural': '测试执行',
                'db_table': 'test_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRunCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('untested', '未测试'), ('passed', '通过'), ('failed', '失败'), ('blocked', '阻塞'), ('retest', '重测')], default='untested', max_length=20, verbose_name='执行状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('comments', models.TextField(blank=True, verbose_name='备注')),
                ('defects', models.JSONField(default=list, verbose_name='关联缺陷')),
                ('elapsed_time', models.DurationField(blank=True, null=True, verbose_name='执行耗时')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_cases', to='executions.testrun', verbose_name='测试执行')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试执行用例',
                'verbose_name_plural': '测试执行用例',
                'db_table': 'test_run_cases',
                'ordering': ['testcase__id'],
                'unique_together': {('test_run', 'testcase')},
            },
        ),
        migrations.CreateModel(
            name='TestRunCaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('untested', '未测试'), ('passed', '通过'), ('failed', '失败'), ('blocked', '阻塞'), ('retest', '重测')], max_length=20, verbose_name='执行状态')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('comments', models.TextField(blank=True, verbose_name='备注')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='执行时间')),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('run_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='executions.testruncase', verbose_name='执行用例')),
            ],
            options={
                'verbose_name': '测试执行历史',
                'verbose_name_plural': '测试执行历史',
                'db_table': 'test_run_case_history',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddField(
            model_name='testrun',
            name='testcases',
            field=models.ManyToManyField(related_name='test_runs', through='executions.TestRunCase', to='testcases.testcase', verbose_name='测试用例'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='versions.version', verbose_name='关联版本'),
        ),
    ]
