SPECTACULAR_SETTINGS = {
    'TITLE': 'TestHub API',
    'DESCRIPTION': 'Test Case Management Platform API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'ENUM_NAME_OVERRIDES': {
        # request/execution/tool enums
        'ApiRequestTypeEnum': 'apps.api_testing.models.ApiRequest.REQUEST_TYPE_CHOICES',
        'AppExecutionResultEnum': 'apps.app_automation.models.AppTestSuite.EXECUTION_RESULT_CHOICES',
        'UiFrameworkEnum': 'apps.ui_automation.models.TestScript.FRAMEWORK_CHOICES',
        'DataFactoryToolScenarioEnum': 'apps.data_factory.models.DataFactoryRecord.TOOL_SCENARIOS',

        # same field name, different choice sets
        'UiElementTypeEnum': 'apps.ui_automation.models.Element.ELEMENT_TYPE_CHOICES',
        'AppElementTypeEnum': 'apps.app_automation.models.AppElement.ELEMENT_TYPE_CHOICES',
        'UiExecutionModeEnum': [('text', '文本模式'), ('vision', '视觉模式')],
        'AiTestingExecutionModeEnum': 'apps.ai_testing.models.AiTestingTask.MODE_CHOICES',
        'UiExecutionStatusEnum': 'apps.ui_automation.models.TestSuite.EXECUTION_STATUS_CHOICES',
        'AppExecutionStatusEnum': 'apps.app_automation.models.AppTestSuite.EXECUTION_STATUS_CHOICES',

        # notification/task/priority
        'ApiNotificationTypeEnum': 'apps.api_testing.models.NotificationLog.NOTIFICATION_TYPES',
        'TaskNotificationTypeEnum': 'apps.api_testing.models.TaskNotificationSetting.NOTIFICATION_TYPES',
        'UiScheduledNotificationTypeEnum': 'apps.ui_automation.models.UiScheduledTask.NOTIFICATION_TYPE_CHOICES',
        'UiNotificationTypeEnum': 'apps.ui_automation.models.UiNotificationLog.NOTIFICATION_TYPES',
        'AppNotificationTypeEnum': 'apps.app_automation.models.AppNotificationLog.NOTIFICATION_TYPES',
        'ManualPriorityEnum': 'apps.testcases.models.TestCase.PRIORITY_CHOICES',
        'ReviewPriorityEnum': 'apps.reviews.models.TestCaseReview.PRIORITY_CHOICES',
        'RequirementPriorityEnum': 'apps.requirement_analysis.models.GeneratedTestCase.PRIORITY_CHOICES',
        'UiPriorityEnum': 'apps.ui_automation.models.TestCase.PRIORITY_CHOICES',
        'RequirementTaskTypeEnum': 'apps.requirement_analysis.models.AnalysisTask.TASK_TYPE_CHOICES',
        'ApiTaskTypeEnum': 'apps.api_testing.models.ScheduledTask.TASK_TYPE_CHOICES',
        'UiTaskTypeEnum': 'apps.ui_automation.models.UiScheduledTask.TASK_TYPE_CHOICES',

        # status enums used across modules
        'ProjectStatusEnum': 'apps.projects.models.Project.STATUS_CHOICES',
        'ManualTestCaseStatusEnum': 'apps.testcases.models.TestCase.STATUS_CHOICES',
        'TestRunStatusEnum': 'apps.executions.models.TestRun.STATUS_CHOICES',
        'TestRunCaseStatusEnum': 'apps.executions.models.TestRunCase.STATUS_CHOICES',
        'ReviewStatusEnum': 'apps.reviews.models.TestCaseReview.STATUS_CHOICES',
        'ReviewAssignmentStatusEnum': 'apps.reviews.models.ReviewAssignment.STATUS_CHOICES',
        'RequirementDocumentStatusEnum': 'apps.requirement_analysis.models.RequirementDocument.STATUS_CHOICES',
        'GeneratedCaseStatusEnum': 'apps.requirement_analysis.models.GeneratedTestCase.STATUS_CHOICES',
        'RequirementTaskStatusEnum': 'apps.requirement_analysis.models.AnalysisTask.STATUS_CHOICES',
        'GenerationTaskStatusEnum': 'apps.requirement_analysis.models.TestCaseGenerationTask.STATUS_CHOICES',
        'ApiProjectStatusEnum': 'apps.api_testing.models.ApiProject.STATUS_CHOICES',
        'ApiExecutionStatusEnum': 'apps.api_testing.models.TestExecution.EXECUTION_STATUS_CHOICES',
        'ApiScheduledTaskStatusEnum': 'apps.api_testing.models.ScheduledTask.STATUS_CHOICES',
        'ApiTaskExecutionStatusEnum': 'apps.api_testing.models.TaskExecutionLog.STATUS_CHOICES',
        'ApiNotificationStatusEnum': 'apps.api_testing.models.NotificationLog.STATUS_CHOICES',
        'UiExecutionRecordStatusEnum': 'apps.ui_automation.models.TestExecution.STATUS_CHOICES',
        'UiCaseStatusEnum': 'apps.ui_automation.models.TestCase.STATUS_CHOICES',
        'UiCaseExecutionStatusEnum': 'apps.ui_automation.models.TestCaseExecution.STATUS_CHOICES',
        'WalletSessionStatusEnum': 'apps.ui_automation.models.WalletSession.STATUS_CHOICES',
        'UiAiExecutionStatusEnum': 'apps.ui_automation.models.AIExecutionRecord.STATUS_CHOICES',
        'AppDeviceStatusEnum': 'apps.app_automation.models.AppDevice.STATUS_CHOICES',
        'AppExecutionStatusTrackEnum': 'apps.app_automation.models.AppTestExecution.STATUS_CHOICES',
        'UnifiedSchedulerRunStatusEnum': 'apps.core.models.UnifiedScheduledJobRun.STATUS_CHOICES',
        'UnifiedSchedulerAlertStatusEnum': 'apps.core.models.UnifiedSchedulerAlert.STATUS_CHOICES',
        'AiTestingTaskStatusEnum': 'apps.ai_testing.models.AiTestingTask.STATUS_CHOICES',
        'AiTestingRunStatusEnum': 'apps.ai_testing.models.AiTestingRun.STATUS_CHOICES',
        'KnowledgeDocumentStatusEnum': 'apps.knowledge_base.models.KnowledgeDocument.STATUS_CHOICES',
        'KnowledgeQueryStatusEnum': 'apps.knowledge_base.models.KnowledgeQuery.STATUS_CHOICES',
        'OcrBatchStatusEnum': 'apps.ocr_service.models.OcrBatch.STATUS_CHOICES',
    },
}
