# Generated by Django 4.2.7 on 2026-04-17 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, verbose_name='套件描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsuites', to='projects.project')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'db_table': 'testsuites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSuiteCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='执行顺序')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testcases.testcase')),
                ('testsuite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsuites.testsuite')),
            ],
            options={
                'verbose_name': '测试套件用例',
                'verbose_name_plural': '测试套件用例',
                'db_table': 'testsuite_cases',
                'ordering': ['order'],
                'unique_together': {('testsuite', 'testcase')},
            },
        ),
        migrations.AddField(
            model_name='testsuite',
            name='testcases',
            field=models.ManyToManyField(through='testsuites.TestSuiteCase', to='testcases.testcase', verbose_name='测试用例'),
        ),
    ]
