# Generated by Django 4.2.7 on 2026-04-25 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_projectmodulebinding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('embedding_provider', models.CharField(blank=True, max_length=100)),
                ('embedding_model', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='projects.project')),
            ],
            options={
                'db_table': 'knowledge_bases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('source_type', models.CharField(choices=[('upload', 'Upload'), ('url', 'URL'), ('text', 'Text')], default='upload', max_length=20)),
                ('source_uri', models.CharField(blank=True, max_length=1000)),
                ('file_name', models.CharField(blank=True, max_length=300)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('content_hash', models.CharField(blank=True, max_length=128)),
                ('content_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to=settings.AUTH_USER_MODEL)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledge_base.knowledgebase')),
            ],
            options={
                'db_table': 'knowledge_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('embedding_ref', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_base.knowledgedocument')),
            ],
            options={
                'db_table': 'knowledge_chunks',
                'ordering': ['document_id', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_queries', to=settings.AUTH_USER_MODEL)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='knowledge_base.knowledgebase')),
            ],
            options={
                'db_table': 'knowledge_queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['knowledge_base', '-created_at'], name='knowledge_q_knowled_567f61_idx'), models.Index(fields=['created_by', '-created_at'], name='knowledge_q_created_385887_idx'), models.Index(fields=['status'], name='knowledge_q_status_7016b3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['knowledge_base', 'status'], name='knowledge_d_knowled_40fcc7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['created_by', '-created_at'], name='knowledge_d_created_11d7b0_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['content_hash'], name='knowledge_d_content_c5b89e_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document', 'chunk_index'], name='knowledge_c_documen_bce51d_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['embedding_status'], name='knowledge_c_embeddi_03c422_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgechunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['project', 'status'], name='knowledge_b_project_fea993_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['created_by', '-created_at'], name='knowledge_b_created_13c70d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgebase',
            unique_together={('project', 'name')},
        ),
    ]
