# Generated by Django 4.2.7 on 2026-04-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='knowledge_base/documents/%Y/%m/'),
        ),
    ]
