# Generated by Django 4.2.7 on 2026-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_knowledgedocument_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding_vector',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
