# Generated by Django 4.2.7 on 2026-04-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_knowledgechunk_embedding_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='vector_store',
            field=models.CharField(choices=[('database', 'Database JSON vectors')], default='database', max_length=50),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding_dimensions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding_provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['embedding_provider'], name='knowledge_b_embeddi_6230d9_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['vector_store'], name='knowledge_b_vector__2d1842_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['embedding_provider', 'embedding_model'], name='knowledge_c_embeddi_e5a68f_idx'),
        ),
    ]
