# Generated by Django 4.2.7 on 2026-04-17 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用于标识该通知配置的名称', max_length=100, verbose_name='配置名称')),
                ('config_type', models.CharField(choices=[('webhook_feishu', '飞书机器人'), ('webhook_wechat', '企业微信机器人'), ('webhook_dingtalk', '钉钉机器人')], default='webhook_feishu', max_length=20, verbose_name='配置类型')),
                ('webhook_bots', models.JSONField(blank=True, default=dict, help_text='飞书、企微、钉钉机器人配置', null=True, verbose_name='Webhook机器人配置')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '统一通知配置',
                'verbose_name_plural': '统一通知配置',
                'db_table': 'unified_notification_configs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['config_type'], name='unified_not_config__ff7bfc_idx'), models.Index(fields=['is_default'], name='unified_not_is_defa_2f6e9a_idx'), models.Index(fields=['is_active'], name='unified_not_is_acti_5d6fa0_idx'), models.Index(fields=['created_by'], name='unified_not_created_a454b7_idx')],
            },
        ),
    ]
