# Generated by Django 4.2.7 on 2026-04-25 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=80)),
                ('source_id', models.PositiveIntegerField()),
                ('job_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('max_attempts', models.PositiveIntegerField(default=1)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_scheduled_job_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unified_scheduled_job_runs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'source_id', '-created_at'], name='unified_sch_module_46a376_idx'), models.Index(fields=['status', '-created_at'], name='unified_sch_status_cc2d88_idx'), models.Index(fields=['triggered_by', '-created_at'], name='unified_sch_trigger_8a4690_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnifiedScheduledJobDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstream_module', models.CharField(max_length=80)),
                ('upstream_source_id', models.PositiveIntegerField()),
                ('downstream_module', models.CharField(max_length=80)),
                ('downstream_source_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_scheduled_job_dependencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unified_scheduled_job_dependencies',
                'ordering': ['downstream_module', 'downstream_source_id', 'upstream_module', 'upstream_source_id'],
                'indexes': [models.Index(fields=['downstream_module', 'downstream_source_id', 'is_active'], name='unified_sch_downstr_71a0ae_idx'), models.Index(fields=['upstream_module', 'upstream_source_id', 'is_active'], name='unified_sch_upstrea_b6f156_idx')],
                'unique_together': {('upstream_module', 'upstream_source_id', 'downstream_module', 'downstream_source_id')},
            },
        ),
    ]
