# Generated by Django 4.2.7 on 2026-04-25 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_unifiedscheduledjobrun_scheduler_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=80)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('run', 'Run'), ('pause', 'Pause'), ('resume', 'Resume')], max_length=40)),
                ('object_type', models.CharField(db_index=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('object_name', models.CharField(blank=True, max_length=255)),
                ('module', models.CharField(blank=True, db_index=True, max_length=80)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('project_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unified_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', '-created_at'], name='unified_aud_domain_641f74_idx'), models.Index(fields=['action', '-created_at'], name='unified_aud_action_58591c_idx'), models.Index(fields=['module', 'source_id', '-created_at'], name='unified_aud_module_d15330_idx'), models.Index(fields=['actor', '-created_at'], name='unified_aud_actor_i_6a8569_idx')],
            },
        ),
    ]
