# Generated by Django 4.2.7 on 2026-04-26 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_unifiedauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedSchedulerAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_key', models.CharField(db_index=True, max_length=180, unique=True)),
                ('alert_type', models.CharField(db_index=True, max_length=80)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('module', models.CharField(blank=True, db_index=True, max_length=80)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('job_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('job_name', models.CharField(blank=True, max_length=255)),
                ('project_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('notify_count', models.PositiveIntegerField(default=0)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_scheduler_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unified_scheduler_alerts',
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['status', '-last_seen_at'], name='unified_sch_status_3dc3f2_idx'), models.Index(fields=['severity', '-last_seen_at'], name='unified_sch_severit_1e719c_idx'), models.Index(fields=['project_id', '-last_seen_at'], name='unified_sch_project_d68a17_idx'), models.Index(fields=['module', 'source_id', '-last_seen_at'], name='unified_sch_module_e62ea9_idx')],
            },
        ),
    ]
