# Generated by Django 4.2.7 on 2026-04-27 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_unifiedscheduleralert'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(db_index=True, max_length=12)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('route_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('query_string', models.TextField(blank=True)),
                ('status_code', models.PositiveIntegerField(db_index=True)),
                ('response_time_ms', models.FloatField(db_index=True)),
                ('request_size', models.PositiveIntegerField(default=0)),
                ('response_size', models.PositiveIntegerField(default=0)),
                ('is_slow', models.BooleanField(db_index=True, default=False)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'request_performance_metrics',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', '-created_at'], name='request_per_path_2f257f_idx'), models.Index(fields=['status_code', '-created_at'], name='request_per_status__98fafe_idx'), models.Index(fields=['is_slow', '-created_at'], name='request_per_is_slow_9440e7_idx'), models.Index(fields=['is_error', '-created_at'], name='request_per_is_erro_0819b9_idx'), models.Index(fields=['user', '-created_at'], name='request_per_user_id_724a6a_idx')],
            },
        ),
    ]
