# Generated by Django 4.2.7 on 2026-04-27 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_requestperformancemetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unifiednotificationconfig',
            name='config_type',
            field=models.CharField(choices=[('email', 'Email'), ('webhook_generic', 'Generic Webhook'), ('webhook_feishu', '飞书机器人'), ('webhook_wechat', '企业微信机器人'), ('webhook_dingtalk', '钉钉机器人')], default='webhook_feishu', max_length=20, verbose_name='配置类型'),
        ),
        migrations.CreateModel(
            name='UnifiedNotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('event_type', models.CharField(choices=[('manual', 'Manual'), ('api_execution', 'API Execution'), ('ui_execution', 'UI Execution'), ('app_execution', 'APP Execution'), ('scheduler_alert', 'Scheduler Alert'), ('requirement', 'Requirement Analysis')], default='manual', max_length=40)),
                ('channel', models.CharField(choices=[('all', 'All Channels'), ('email', 'Email'), ('webhook', 'Webhook')], default='all', max_length=20)),
                ('subject_template', models.CharField(blank=True, max_length=255)),
                ('body_template', models.TextField()),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('html', 'HTML')], default='markdown', max_length=20)),
                ('variables_schema', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unified_notification_templates',
                'ordering': ['event_type', '-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedNotificationSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook')], max_length=20)),
                ('target', models.CharField(blank=True, max_length=500)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='core.unifiednotificationconfig')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_send_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_logs', to='core.unifiednotificationtemplate')),
            ],
            options={
                'db_table': 'unified_notification_send_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='unifiednotificationtemplate',
            index=models.Index(fields=['event_type', 'channel', 'is_active'], name='unified_not_event_t_14a928_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiednotificationtemplate',
            index=models.Index(fields=['is_default'], name='unified_not_is_defa_55e836_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiednotificationtemplate',
            index=models.Index(fields=['created_by'], name='unified_not_created_b0f258_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiednotificationsendlog',
            index=models.Index(fields=['channel', '-created_at'], name='unified_not_channel_7508da_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiednotificationsendlog',
            index=models.Index(fields=['status', '-created_at'], name='unified_not_status_516c09_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiednotificationsendlog',
            index=models.Index(fields=['config', '-created_at'], name='unified_not_config__081bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiednotificationsendlog',
            index=models.Index(fields=['template', '-created_at'], name='unified_not_templat_e8c414_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiednotificationsendlog',
            index=models.Index(fields=['created_by', '-created_at'], name='unified_not_created_686128_idx'),
        ),
    ]
