# Generated by Django 4.2.7 on 2026-04-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='extractors',
            field=models.JSONField(blank=True, default=list, verbose_name='Response extractors'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='parameterized_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Parameterized data sets'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='parameterized_enabled',
            field=models.BooleanField(default=False, verbose_name='Parameterized execution enabled'),
        ),
    ]
