# Generated by Django 4.2.7 on 2026-05-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0002_apirequest_extractors_testsuite_parameterized_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='report_error',
            field=models.TextField(blank=True, default='', verbose_name='报告生成错误信息'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='report_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报告生成完成时间'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='report_status',
            field=models.CharField(choices=[('IDLE', '未生成'), ('PENDING', '排队中'), ('GENERATING', '生成中'), ('READY', '已就绪'), ('FAILED', '生成失败')], default='IDLE', max_length=20, verbose_name='报告生成状态'),
        ),
    ]
