# Generated by Django 4.2.7 on 2026-05-01 10:51

import apps.core.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_testing', '0003_testexecution_report_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiserviceconfig',
            name='api_key',
            field=apps.core.encrypted_fields.EncryptedCharField(max_length=2048, verbose_name='API Key'),
        ),
    ]
