# Generated by Django 4.2.7 on 2026-04-30 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(message='手机号格式无效', regex='^\\+?[\\d\\-\\s]{6,32}$')], verbose_name='手机号'),
        ),
    ]
