# Generated by Django 4.2.7 on 2026-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0005_walletsession_process_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiexecutionrecord',
            name='execution_mode',
            field=models.CharField(choices=[('text', '文本模式'), ('vision', '视觉模式')], default='text', max_length=20, verbose_name='执行模式'),
        ),
    ]
