# Generated by Django 4.2.7 on 2026-04-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0006_alter_aiexecutionrecord_execution_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['page', 'sort_order', 'name'], 'verbose_name': 'UI元素', 'verbose_name_plural': 'UI元素'},
        ),
        migrations.AddField(
            model_name='element',
            name='fallback_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='element',
            name='last_used_locator',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='element',
            name='locator_failure_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='element',
            name='locator_success_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='element',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='element',
            index=models.Index(fields=['project', 'page', 'sort_order'], name='ui_elements_project_25d036_idx'),
        ),
    ]
