# Generated by Django 4.2.7 on 2026-04-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdevice',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appdevice',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appdevice',
            name='pool_name',
            field=models.CharField(blank=True, default='default', max_length=120),
        ),
        migrations.AddField(
            model_name='appdevice',
            name='scrcpy_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appdevice',
            name='scrcpy_status',
            field=models.CharField(blank=True, default='stopped', max_length=20),
        ),
        migrations.AddField(
            model_name='appdevice',
            name='scrcpy_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='appdevice',
            name='connection_type',
            field=models.CharField(choices=[('usb', 'USB'), ('emulator', '本地模拟器'), ('remote_emulator', '远程模拟器'), ('real_device', '真实设备')], default='emulator', max_length=20, verbose_name='连接类型'),
        ),
        migrations.AddIndex(
            model_name='appdevice',
            index=models.Index(fields=['pool_name', 'status'], name='app_devices_pool_na_3103f6_idx'),
        ),
        migrations.AddIndex(
            model_name='appdevice',
            index=models.Index(fields=['last_seen_at'], name='app_devices_last_se_6552ba_idx'),
        ),
    ]
