# Generated by Django 4.2.7 on 2026-04-25 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_unifiedtestasset_unifiedtestassetsnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTestingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('instruction', models.TextField()),
                ('target_url', models.CharField(blank=True, max_length=1000)),
                ('execution_mode', models.CharField(choices=[('browser_text', 'Browser text'), ('browser_vision', 'Browser vision')], default='browser_text', max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('browser_config', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_testing_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_testing_tasks', to='projects.project')),
            ],
            options={
                'db_table': 'ai_testing_tasks',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AiTestingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('instruction_snapshot', models.TextField(blank=True)),
                ('target_url_snapshot', models.CharField(blank=True, max_length=1000)),
                ('execution_mode', models.CharField(choices=[('browser_text', 'Browser text'), ('browser_vision', 'Browser vision')], default='browser_text', max_length=40)),
                ('planned_steps', models.JSONField(blank=True, default=list)),
                ('executed_steps', models.JSONField(blank=True, default=list)),
                ('artifacts', models.JSONField(blank=True, default=dict)),
                ('cost', models.JSONField(blank=True, default=dict)),
                ('logs', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_testing_runs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_testing_runs', to='projects.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ai_testing.aitestingtask')),
            ],
            options={
                'db_table': 'ai_testing_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aitestingtask',
            index=models.Index(fields=['project', 'status'], name='ai_testing__project_d4e5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='aitestingtask',
            index=models.Index(fields=['created_by', '-created_at'], name='ai_testing__created_c3d0fc_idx'),
        ),
        migrations.AddIndex(
            model_name='aitestingtask',
            index=models.Index(fields=['execution_mode'], name='ai_testing__executi_c3f4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='aitestingrun',
            index=models.Index(fields=['project', 'status'], name='ai_testing__project_fcef8a_idx'),
        ),
        migrations.AddIndex(
            model_name='aitestingrun',
            index=models.Index(fields=['task', '-created_at'], name='ai_testing__task_id_a2bcf0_idx'),
        ),
        migrations.AddIndex(
            model_name='aitestingrun',
            index=models.Index(fields=['created_by', '-created_at'], name='ai_testing__created_15e5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='aitestingrun',
            index=models.Index(fields=['status', '-created_at'], name='ai_testing__status_6c9f2c_idx'),
        ),
    ]
