# Generated by Django 4.2.7 on 2026-04-17 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('testcases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待评审'), ('approved', '已通过'), ('rejected', '已拒绝'), ('abstained', '弃权')], default='pending', max_length=20, verbose_name='评审状态')),
                ('comment', models.TextField(blank=True, verbose_name='评审意见')),
                ('checklist_results', models.JSONField(blank=True, default=dict, verbose_name='检查清单结果')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='评审时间')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分配时间')),
            ],
            options={
                'verbose_name': '评审分配',
                'verbose_name_plural': '评审分配',
                'db_table': 'review_assignments',
            },
        ),
        migrations.CreateModel(
            name='ReviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('checklist', models.JSONField(default=list, verbose_name='检查清单')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('default_reviewers', models.ManyToManyField(blank=True, related_name='template_reviews', to=settings.AUTH_USER_MODEL, verbose_name='默认评审人')),
                ('project', models.ManyToManyField(related_name='review_templates', to='projects.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '评审模板',
                'verbose_name_plural': '评审模板',
                'db_table': 'review_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='评审标题')),
                ('description', models.TextField(blank=True, verbose_name='评审描述')),
                ('status', models.CharField(choices=[('pending', '待评审'), ('in_progress', '评审中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='评审状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='截止日期')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reviews', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('projects', models.ManyToManyField(related_name='reviews', to='projects.project', verbose_name='关联项目')),
                ('reviewers', models.ManyToManyField(related_name='assigned_reviews', through='reviews.ReviewAssignment', to=settings.AUTH_USER_MODEL, verbose_name='评审人员')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_reviews', to='reviews.reviewtemplate', verbose_name='使用的模板')),
                ('testcases', models.ManyToManyField(related_name='reviews', to='testcases.testcase', verbose_name='评审用例')),
            ],
            options={
                'verbose_name': '测试用例评审',
                'verbose_name_plural': '测试用例评审',
                'db_table': 'testcase_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('general', '整体意见'), ('testcase', '用例意见'), ('step', '步骤意见')], default='general', max_length=20, verbose_name='意见类型')),
                ('content', models.TextField(verbose_name='意见内容')),
                ('step_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='步骤序号')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.testcasereview', verbose_name='评审')),
                ('testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='testcases.testcase', verbose_name='相关用例')),
            ],
            options={
                'verbose_name': '评审意见',
                'verbose_name_plural': '评审意见',
                'db_table': 'review_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.testcasereview', verbose_name='评审'),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评审人'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together={('review', 'reviewer')},
        ),
    ]
